### ISSUE TITLE
Craters are drawn in the wrong order

### ISSUE THREAD

**Issue by Ratysz** [RWA-Team/RimworldAscension#40] opened 2016-05-26 20:32 UTC
At the beginning of the game, craters are not layered on top of each other properly, sometimes resulting in craters made by earlier debris being drawn on top of those made after.

**Comment by Wivex** [comment] 2016-05-26 20:45
need to adjust each next crater draw altitude by some small amount

**Comment by campaignupgrade** [comment] 2016-05-27 15:16
overlapping craters sometimes flicker. i suspect this is the same issue.

**Comment by Wivex** [comment] 2016-05-27 15:33
it is. The cause of it is unknown, but it should be fixed by different draw altitudes

**Comment by Wivex** [comment] 2016-06-07 19:41
fixed

**Closed as completed by Wivex** 2016-06-07 19:41 UTC
Labels: Bug
